# Generated by Django 5.2.16 on 2026-07-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=100)),
                ('subtitle', models.CharField(blank=True, default='Learn who we are and why we exist', max_length=180)),
                ('overview', models.TextField(blank=True, default='We are a learning platform committed to helping students and professionals grow through high-quality courses, mentorship, and community support.')),
                ('mission', models.TextField(blank=True, default='To empower every learner with access to practical skills and guidance so they can achieve their goals confidently.')),
                ('vision', models.TextField(blank=True, default='To become the trusted destination for career-ready education and lifelong growth.')),
                ('values', models.TextField(blank=True, default='Integrity, excellence, student-first service, and continuous innovation.')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us Content',
                'verbose_name_plural': 'About Us Content',
            },
        ),
    ]
