# Generated by Django 5.2.16 on 2026-08-29 18:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybee', '0005_customuser_is_email_verified_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Python Programming - Functions', max_length=180)),
                ('subject', models.CharField(default='Python', max_length=150)),
                ('course_name', models.CharField(default='Python Programming', max_length=200)),
                ('instructor_name', models.CharField(default='Rahul Sharma', max_length=150)),
                ('instructor_profile', models.CharField(blank=True, default='Senior Python Trainer', max_length=180)),
                ('class_date', models.DateField(default=django.utils.timezone.now)),
                ('class_time', models.TimeField(default='10:00:00')),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('student_count', models.PositiveIntegerField(default=125)),
                ('live_indicator', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='Interactive live class with hands-on coding exercises and Q&A.')),
                ('join_link', models.URLField(blank=True, default='https://example.com/live-class')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Live Class',
                'verbose_name_plural': 'Live Classes',
                'ordering': ['-class_date', '-class_time'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveClassResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('resource_type', models.CharField(default='PDF', max_length=80)),
                ('file_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='studybee.liveclass')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
