# Generated by Django 5.2.16 on 2026-08-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybee', '0006_liveclass_chatmessage_liveclassresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(default='Learning', max_length=80)),
                ('summary', models.TextField(max_length=300)),
                ('content', models.TextField(blank=True)),
                ('author', models.CharField(default='StudyBee Team', max_length=120)),
                ('reading_time', models.CharField(default='5 min read', max_length=30)),
                ('published_at', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
